### ISSUE TITLE
Faculty and Staff page: Navigation

### ISSUE THREAD

**Issue by masoneli** [phoenixMag00/Kuma#28]
Please put an "All" button on the Faculty/Staff page so that when viewing separate employee types it's possible to go back "home." 

Also, please make it possible to force the display order of the employee types so that they can follow the bureaucratic hierarchy (if desired) instead of alphabetical order. Mwahaha. Staff first, of course.

**Comment by phoenixMag00** [comment]
I will add this in a next release (v. 1.1.2?). Hopefully should be ready for download by mid-March 2013.

**Comment by phoenixMag00** [comment]
The All link has been added! This one is for masoneli. I also want to thank Karen for helping me find the solution.

Now, I haven't changed the sort abilities for the Taxonomy. Still want to think about that for a little.

Masoneli: I have opened up a new issue for your request.
