### ISSUE TITLE
Faculty/Staff as child page

### ISSUE THREAD

**Issue by masoneli** [phoenixMag00/Kuma#29]
We want the Faculty/Staff page as a child page. 

Karen Wolf set it up for me in the kuma-cub child theme, but when I click on the employee types the page goes back to full-width:

http://tuscany.gmu.edu/depts/unilife/eli/teaching/faculty-and-staff/

Word on the street is that this is because of category pages and it will be complicated to set it up in an ideal way, but if it's possible, I'd like it to do that.

**Comment by phoenixMag00** [comment]
In your child theme, add the column code to the templates that control the layout. You should have to modify the two taxonomy templates. I'm sure Karen can help you with that.
