### ISSUE TITLE
Auxiliary Menu only allows 7 links

### ISSUE THREAD

**Issue by masoneli** [phoenixMag00/Kuma#30]
It seems like the auxiliary menu in Kuma only allows 7 links. I want 8. I might want more in the future. Is there a way to fix that in the child theme?

While best practice might dictate no more that 7 links (I'm guessing that's the rationale for the limit), we're using it for links to foreign language applications. If it's possible to expand the aux menu, we'd like to be able to do it. 

http://tuscany.gmu.edu/depts/unilife/eli/

Addendum: Looks like the 8th link is there when I use the ipad (but partially covered). Is there an easy way I can make sure the header expands to a width that would allow it to be seen on the front page in a computer browser? Is there a way to make a second column of links possible?

Of all the many potential changes I've asked about, this one is probably the most urgent according to the director.

**Comment by phoenixMag00** [comment]
Hmmm. I really can't add more space up there, but I have a feeling that if you use a child theme then you could restyle the text to be smaller. You could totally also make the auxiliary nav two columns with just CSS. I would go with a child theme solution, however, you could use a plugin to inject the CSS and override the parent theme.
