### ISSUE TITLE
Minor Accessibility Issues with 404 Page

### ISSUE THREAD

**Issue by kate515** [phoenixMag00/Kuma#31]
Best Practice: Ensure new windows or frames do not open without a warning(Severity: Medium)
Line: 150   

a class="the-social-network text-swap" id="mobile-mason" target="_blank" href="http://gettheapp.gmu.edu/?utm_source=kuma_theme&utm_medium=footer_icon&utm_campaign=gettheapp"

Anchor target is new window or frame

Best Practice: Provide valid labels for form fields(Severity: High)
Line: 108  
input type="text" maxlength="600" class="text" name="q"

Provide explicit labels for form fields

**Comment by phoenixMag00** [comment]
These will be updated in the latest release slated for mid-february 2013

**Comment by phoenixMag00** [comment]
Field Label has been added. I'm leaving the _blank targets for now....
